<a href="https://colab.research.google.com/github/Sahajkaur23/bigdata--assignment/blob/main/202301053_ass2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
arr = np.array([1, 2, 3, 6, 4, 5])
reverse_arr = arr[::-1]
print(reverse_arr)

[5 4 6 3 2 1]


In [2]:
import numpy as np
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[1, 2], [3, 4]])
if np.array_equal(arr1, arr2):
    print("true")
else:
    print("false")




true


In [3]:
import numpy as np
x= np.array([1,2,3,4,5,1,2,1,1,1])
freq_x = np.argmax(np.bincount(x))
print("The most frequent value in x is",freq_x)
indices_x = np.where(x == freq_x)[0]
print("The indices of the most frequent value in x are", indices_x)
y=np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])
freq_y = np.argmax(np.bincount(y))
print("The most frequent value in y is",freq_y)
indices_y = np.where(x == freq_y)[0]
print("The indices of the most frequent value in x are", indices_y)

The most frequent value in x is 1
The indices of the most frequent value in x are [0 5 7 8 9]
The most frequent value in y is 1
The indices of the most frequent value in x are [0 5 7 8 9]


In [5]:
import numpy as np
gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')
row_sum = gfg.sum(axis=1)
col_sum = gfg.sum(axis=0)
print(row_sum)
print(col_sum)



[[14]
 [16]
 [15]]
[[20  9 16]]
