<a href="https://colab.research.google.com/github/Sahajkaur23/bigdata--assignment/blob/main/assignment1_202301053.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
arr = np.array([1, 2, 3, 6, 4, 5])
rev_arr=arr[::-1]
print(rev_arr)

[5 4 6 3 2 1]


In [ ]:
import numpy as np;

arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[1, 2], [3, 4]])
compare=(np.array_equal(arr1,arr2))
print(compare)

True


In [ ]:
x = np.array([1,2,3,4,5,1,2,1,1,1])
count=np.bincount(x)
freq_val=np.argmax(count)
print(freq_val)

indices=np.where(x==freq_val)[0]
print(indices)


y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])
count1=np.bincount(y)
freq_val1=np.argmax(count1)
print(freq_val1)

indice=np.where(y==freq_val1)[0]
print(indice)


1
[0 5 7 8 9]
1
[0 1 2]


In [ ]:
Matrix=np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')
print(np.sum(Matrix))

row=np.sum(Matrix,axis=1)
print(row)
column=np.sum(Matrix,axis=0)
print(column)


45
[[14]
 [16]
 [15]]
[[20  9 16]]
